#! /usr/bin/env python

'''
Make rdesktop behave more cleverly
'''

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import subprocess
import sys
import getpass
from PySide.QtGui import QMainWindow, QApplication

class MainWindow(QMainWindow): # pylint: disable=R0904
    '''
    Calibration window
    '''

    def __init__(self, app, parent=None):
        super(MainWindow, self).__init__(parent)
        self.app = app
        self.fitsize = None

    def resizeEvent(self, event): # pylint: disable=C0103
        fitsize = (event.size().width(), event.size().height())
        if self.size:
            self.fitsize = fitsize
            self.app.quit()
        else:
            self.fitsize = fitsize

def getfitsize():
    '''
    Get current Notion frame size
    '''

    app = QApplication(sys.argv)
    win = MainWindow(app)
    win.show()
    app.exec_()

    return win.fitsize

def rdesktop(server, user, domain, width, height):
    '''
    Run rdesktop
    '''

    # TODO Remove ~/.rdesktop? (Doesn't seem needed anymore)

    args = ['rdesktop', '-u', user, '-d', domain, '-g%dx%d' % (width, height),
            '-K', server]
    subprocess.call(args)

def main():
    '''
    Main function
    '''

    parser = ArgumentParser(description="make rdesktop behave more cleverly",
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('-s', '--server', help="remote server")
    parser.add_argument('-u', '--user', default=getpass.getuser(),
                        help="username for authentication on the server")
    parser.add_argument('-d', '--domain', help="domain for authentication")
    args = parser.parse_args()

    width, height = getfitsize()
    rdesktop(args.server, args.user, args.domain, width, height)

if __name__ == '__main__':
    sys.exit(main())
